# Generated by Django 2.2 on 2019-05-16 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120, unique=True, verbose_name='Nazwa użytkownika')),
                ('password', models.CharField(default='', max_length=20, verbose_name='Hasło')),
                ('password2', models.CharField(default='', max_length=20, verbose_name='Potwierdż hasło')),
                ('city', models.CharField(max_length=120, verbose_name='Miasto zamieszkania')),
                ('email', models.EmailField(default='', max_length=254, unique=True, verbose_name='Adres email')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
