# Generated by Django 2.2.1 on 2019-05-24 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Tytuł')),
                ('category', models.CharField(max_length=120, verbose_name='Kategoria')),
                ('description', models.TextField(default='', verbose_name='Opis')),
                ('min_number_of_players', models.IntegerField(default='', verbose_name='Minimalna liczba graczy')),
                ('max_number_of_players', models.IntegerField(default='', verbose_name='Maksymalna liczba graczy')),
                ('min_age', models.IntegerField(blank=True, default='', verbose_name='Minimalny wiek gracza')),
                ('image', models.ImageField(blank=True, upload_to='gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=120, verbose_name='Miasto zamieszkania')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
