# Generated by Django 2.2.1 on 2019-05-31 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Tytuł')),
                ('category', models.CharField(choices=[('', 'Wybierz kategorię gry'), ('strategiczna', 'strategiczna'), ('towarzyska', 'towarzyska'), ('karciana', 'karciana'), ('rodzinna', 'rodzinna'), ('ekonomiczna', 'ekonomiczna'), ('przygodowa', 'przygodowa'), ('logiczna', 'logiczna'), ('kooperacyjna', 'kooperacyjna'), ('zręcznościowa', 'zręcznościowa'), ('podróżna', 'podróżna')], max_length=120, verbose_name='Kategoria')),
                ('description', models.TextField(default='Opis', verbose_name='Opis')),
                ('min_number_of_players', models.IntegerField(default=0, verbose_name='Minimalna liczba graczy')),
                ('max_number_of_players', models.IntegerField(blank=True, default=0, verbose_name='Maksymalna liczba graczy')),
                ('min_age', models.IntegerField(blank=True, default=0, verbose_name='Minimalny wiek gracza')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=120, verbose_name='Miasto zamieszkania')),
                ('owned_product', models.ManyToManyField(to='sharing_app.Product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
