# Generated by Django 2.2 on 2019-05-17 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharing_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
