# Generated by Django 2.2.1 on 2019-05-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('', 'Wybierz kategorię'), ('strategiczne', 'strategiczne'), ('towarzyskie', 'towarzyskie'), ('karciane', 'karciane'), ('rodzinne', 'rodzinne'), ('ekonomiczne', 'ekonomiczne'), ('przygodowe', 'przygodowe'), ('logiczne', 'logiczne'), ('kooperacyjne', 'kooperacyjne'), ('zręcznościowe', 'zręcznościowe'), ('podróżne', 'podróżne')], max_length=120, verbose_name='Kategoria'),
        ),
    ]
