# Generated by Django 2.2.1 on 2019-06-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='max_number_of_players',
            field=models.IntegerField(blank=True, default=1, verbose_name='Maksymalna liczba graczy'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_age',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Minimalny wiek gracza'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_number_of_players',
            field=models.IntegerField(default=1, verbose_name='Minimalna liczba graczy'),
        ),
    ]
