# Generated by Django 2.2 on 2019-05-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True, verbose_name='Adres email'),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='', max_length=120, unique=True, verbose_name='Nazwa użytkownika'),
        ),
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default='', max_length=20, verbose_name='Hasło'),
        ),
        migrations.AddField(
            model_name='profile',
            name='password2',
            field=models.CharField(default='', max_length=20, verbose_name='Potwierdż hasło'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=120, verbose_name='Miasto zamieszkania'),
        ),
    ]
