# Generated by Django 2.2.1 on 2019-05-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing_app', '0002_auto_20190525_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='owned_product',
            field=models.ManyToManyField(to='sharing_app.Product'),
        ),
    ]
