# Generated by Django 2.2.1 on 2019-05-23 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharing_app', '0002_auto_20190523_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='max_number_of_gamers',
            new_name='max_number_of_players',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='min_number_of_gamers',
            new_name='min_number_of_players',
        ),
    ]
