# Generated by Django 2.2.1 on 2019-06-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing_app', '0002_productprofile_user_have'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('added', 'added'), ('pending', 'pending'), ('deleted', 'deleted'), ('withdraw', 'withdraw')], default='pending', max_length=120),
        ),
    ]
