# Generated by Django 2.2.1 on 2019-05-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing_app', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Tytuł')),
                ('category', models.CharField(max_length=120, verbose_name='Kategoria')),
                ('description', models.TextField()),
                ('min_number_of_gamers', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
